CREATE TABLE users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(40) NOT NULL,
    login varchar(25) NOT NULL,
    name varchar(25) DEFAULT 'user_abuser',
    birthday date
);

CREATE TABLE mpa (
    id   INTEGER PRIMARY KEY,
    name VARCHAR(10) NOT NULL
);

CREATE TABLE films (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title varchar(40) NOT NULL,
    description varchar(100) DEFAULT 'Какое-то описание, очень интересное',
    release_date date NOT NULL,
    likes_count integer DEFAULT 0,
    duration integer,
    mpa_id integer,
    CONSTRAINT mpa_pk FOREIGN KEY (mpa_id) REFERENCES mpa(id),
    CONSTRAINT empty_title CHECK title <> ''
);

CREATE TABLE genre (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(40) NOT NULL
);

CREATE TABLE film_genre (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_id integer,
    genre_id integer,
    CONSTRAINT film_genre_films_pk FOREIGN KEY (film_id) REFERENCES films(id),
    CONSTRAINT film_genre_genre_pk FOREIGN KEY (genre_id) REFERENCES genre(id)
);

CREATE TABLE like_users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer,
    film_id integer,
    CONSTRAINT user_pk FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT film_pk FOREIGN KEY (film_id) REFERENCES films(id),
    UNIQUE(user_id, film_id)
);

CREATE TABLE friendship (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer,
    friend_id integer,
    status varchar(30) DEFAULT 'PENDING',
    CONSTRAINT friendship_user_pk FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT friendship_friend_pk FOREIGN KEY (friend_id) REFERENCES users(id)
);

INSERT INTO mpa (id, name) VALUES
(1, 'G'),
(2, 'PG'),
(3, 'PG-13'),
(4, 'R'),
(5, 'NC-17');

INSERT INTO users (id, name, email, login, birthday) VALUES
(1, 'Gde1', 'Gde1_email@', 'Gde228_1337_1', '2001-01-01'),
(2, 'Gde2', 'Gde2_email@', 'Gde228_1337_2', '2002-02-02');

INSERT INTO films (id, title, description, release_date,duration,mpa_id)
VALUES (1,'Film1','description1','2001-01-01',121,1),
(2,'Film2','description2','2002-02-02',122,2);

INSERT INTO genre (id, name)
VALUES
    (1, 'Комедия'),
    (2, 'Драма'),
    (3, 'Мультфильм'),
    (4, 'Триллер'),
    (5, 'Документальный'),
    (6, 'Боевик');




