CREATE TABLE users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(40) NOT NULL,
    login varchar(25) NOT NULL,
    name varchar(25) DEFAULT 'user_abuser',
    birthday date NOT  NULL
);

CREATE TABLE films (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title varchar(40) NOT NULL,
    description varchar(100) DEFAULT 'Какое-то описание, очень интересное',
    release_date date NOT NULL,
    likes_count integer DEFAULT 0,
    duration integer,
    rating varchar(20),
    CONSTRAINT empty_title CHECK title <> ''
);

CREATE TABLE genre (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(40) NOT NULL
);

CREATE TABLE film_genre (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_id integer,
    genre_id integer,
    CONSTRAINT film_genre_films_pk FOREIGN KEY (film_id) REFERENCES films(id),
    CONSTRAINT film_genre_genre_pk FOREIGN KEY (genre_id) REFERENCES genre(id)
);

CREATE TABLE like_users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer,
    film_id integer,
    CONSTRAINT user_pk FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT film_pk FOREIGN KEY (film_id) REFERENCES films(id),
    UNIQUE(user_id, film_id)
);

CREATE TABLE friendship (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer,
    friend_id integer,
    status varchar(30) DEFAULT 'PENDING',
    CONSTRAINT friendship_user_pk FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT friendship_friend_pk FOREIGN KEY (friend_id) REFERENCES users(id)
);

INSERT INTO users (id, name, email, login, birthday) VALUES
(1, 'Gde1', 'Gde1_email@', 'Gde228_1337_1', '2001-01-01'),
(2, 'Gde2', 'Gde2_email@', 'Gde228_1337_2', '2002-02-02');

INSERT INTO films (id, title, description, release_date,duration,rating)
VALUES (1,'Film1','description1','2001-01-01',121,'"PG-13'),
(2,'Film2','description2','2002-02-02',122,'"PG-13');

INSERT INTO genre (id, name)
VALUES (1, 'genre1'),
(2,'genre2'),
(3,'genre3')



